// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5iaVp1iMBHSVCvfevfH57vDCcHELMBNc',
    appId: '1:867917071065:web:310907797867f3d579b4c8',
    messagingSenderId: '867917071065',
    projectId: 'mindwell-ai-a7c7e',
    authDomain: 'mindwell-ai-a7c7e.firebaseapp.com',
    storageBucket: 'mindwell-ai-a7c7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgaEkIjEtSgw_PLaaCS8yYk11OcyZlF8s',
    appId: '1:867917071065:android:0c871b5e5bd7547a79b4c8',
    messagingSenderId: '867917071065',
    projectId: 'mindwell-ai-a7c7e',
    storageBucket: 'mindwell-ai-a7c7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhpd0B0utYZs0Iw7N7RUyXw2enKvj0NNU',
    appId: '1:867917071065:ios:b98f00264c0407ad79b4c8',
    messagingSenderId: '867917071065',
    projectId: 'mindwell-ai-a7c7e',
    storageBucket: 'mindwell-ai-a7c7e.firebasestorage.app',
    iosBundleId: 'com.example.mindwellAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhpd0B0utYZs0Iw7N7RUyXw2enKvj0NNU',
    appId: '1:867917071065:ios:b98f00264c0407ad79b4c8',
    messagingSenderId: '867917071065',
    projectId: 'mindwell-ai-a7c7e',
    storageBucket: 'mindwell-ai-a7c7e.firebasestorage.app',
    iosBundleId: 'com.example.mindwellAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5iaVp1iMBHSVCvfevfH57vDCcHELMBNc',
    appId: '1:867917071065:web:e99d3eb8423a400079b4c8',
    messagingSenderId: '867917071065',
    projectId: 'mindwell-ai-a7c7e',
    authDomain: 'mindwell-ai-a7c7e.firebaseapp.com',
    storageBucket: 'mindwell-ai-a7c7e.firebasestorage.app',
  );
}
